config/routes.rb
Rails.application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  resources :pictures do
      collection do
          post :confirm
      end
  end

  resources :favorites
  root to: 'pictures#index'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy

  has_many :favorite_users, through: :favorites, source: :user
  
  mount_uploader :image, ImageUploader

end

app/models/user.rb
class User < ApplicationRecord

    before_validation { email.downcase! }

    validates :name, presence: true, length: { maximum: 30 }
    validates :email, presence: true, length: { maximum: 255 }, uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

    has_many :pictures
    has_many :favorites, dependent: :destroy

    mount_uploader :avatar, AvatarUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(picture_id: params[:picture_id])
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんの投稿をお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to pictures_url, notice: "#{favorite.picture.user.name}さんの投稿をお気に入り解除しました"
  end

  def index
    @user = current_user
    @favorites = Favorite.where(user_id: @user.id).all
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

    before_action :set_picture, only: [:show, :edit, :update, :destroy]

    before_action :sign_in_user

    before_action :ensure_correct_user, {only: [:edit, :update, :destroy]}


    def index
      @pictures = Picture.all
    end

    def new
      if params[:back]
        @picture = Picture.new(picture_params)
      else
        @picture = Picture.new
      end
    end

    def create
      @picture = Picture.new(picture_params)
      @picture.user_id = current_user.id
      if @picture.save
        redirect_to pictures_path, notice: "画像をアップロードしました!"
      else
        render 'new'
      end
    end

    def show
      @favorite = current_user.favorites.find_by(picture_id: @picture.id)
    end

    def edit
    end

    def update
      if @picture.update(picture_params)
        redirect_to pictures_path, notice: "投稿を編集しました！"
      else
        render 'edit'
      end
    end

    def destroy
      @picture.destroy
      redirect_to pictures_path, notice: "画像を削除しました！"
    end


    def confirm
      @picture = Picture.new(picture_params)
      @picture.user_id = current_user.id
      render :new if @picture.invalid?
    end

    private

    def picture_params
      params.require(:picture).permit(:content, :user_id, :image, :image_cache)
    end

    def set_picture
      @picture = Picture.find(params[:id])
    end

    def sign_in_user
      redirect_to new_user_path unless logged_in?
    end


    def ensure_correct_user
      @picture = Picture.find_by(id: params[:id])
      if current_user.id != @picture.user_id
        flash[:notice] = "権限がありません"
        redirect_to root_path
      end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_user, only: [:show, :edit, :update]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to user_path(@user.id)
        else
            render 'new'
        end
    end

    def show
        @user = User.find(params[:id])
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      if @user.update(user_params)
        redirect_to user_path, notice: "プロフィールを編集しました！"
      else
        render 'edit'
      end
    end


    private

    def user_params
        params.require(:user).permit(:name, :email, :password, :pasword_confirmation, :avatar, :avatar_cache)
    end

    def set_user
      @user = User.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
  def choose_new_or_edit
      if action_name == 'new' || action_name == 'confirm'
          confirm_pictures_path
      elsif action_name == 'edit'
          picture_path
      end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
      current_user.present?
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/index.html.erb
<h1>お気に入り</h1>


<% @favorites.each do |favorite| %>
  <% picture = Picture.find(favorite.picture_id) %>
    <%= picture.content %><br>
    <%= image_tag(picture.image.url) if picture.image && picture.image.url %><br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictgram</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <header>
      <ul>

      <% if logged_in? %>
      <li><%= link_to current_user.name, user_path(current_user.id) %></li>
      <li><%= link_to "ホーム", pictures_path %></li>
      <li><%= link_to "お気に入り", favorites_path %></li>
      <li><a href="#">友達を検索</a></li>
      <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
      <% else %>
      <li><%= link_to "Login", new_session_path %></li>

    <% end %>

    </ul>
  </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <%= yield %>

<div class="push"></div>

  <footer>
    <div class="container">
      <p class="text-muted">
        <span>Pictgramについて</span>
        <span>サポート</span>
        <span>プレス</span>
        <span>API</span>
        <span>求人</span>
        <span>プライバシー</span>
        <span>利用規約</span>
        <span>ディレクトリ</span>
        <span>プロフィール</span>
        <span>ハッシュタグ</span>
        <span>言語</span>
      </p>
      </div>
  </footer>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: @picture, local: true, url: choose_new_or_edit ) do |form| %>
<% if @picture.errors.any? %>
<div id="error_explanation">
    <h2><%= @picture.errors.count %>件のエラーがあります。</h2>
    <ul>
        <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="container">
<div class="picture_content">
<div class="form-group">
    <%= form.label "画像をアップロード" %>
    <% if @picture.image.present? %>
    <%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
    <% end %>
    <%= form.file_field :image, class: "form-control" %><br>
    <%= form.hidden_field :image_cache %>
    <%= form.text_area :content, class: "form-control", placeholder: "コメント" %><br>
    <%= form.submit "アップロード", class: 'btn btn-success' %>
<% end %>
 </div>
</div>
</div>

app/views/pictures/confirm.html.erb
<h3>以下の内容で、アップロードする。</h3>

<%= form_with(model: @picture, url: pictures_path, local: true) do |form| %>
<%= form.hidden_field :content %>

<%= image_tag(@picture.image.url) if @picture.image && @picture.image.url %>
<%= form.hidden_field :image_cache %>

<p>コメント: <%= @picture.content %></p>

<%= form.submit "登録する", class: 'btn btn-success' %>

<% end %>

<%= form_with(model: @picture, url: new_picture_path, local: true, method: 'get') do |form| %>
<%= form.hidden_field :content %>
<%= form.hidden_field :image_cache %>

<%= form.submit "戻る", name: 'back', class: 'btn btn-info' %>
<% end %>

app/views/pictures/edit.html.erb
<h2>投稿を編集する</h2>
<%= render 'form' %>

app/views/pictures/index.html.erb
<br>

<div class="container">
<div class="picturelist">
<%= link_to '投稿を作成', new_picture_path, class: "btn btn-info" %>

<div class="push"></div>
<table align="center">
  <% @pictures.each do |picture| %>
    <tr>
      <td colspan="3" width="400" height=auto align="left"><font size="4rem">
        <%= link_to picture.user.name, user_path(picture.user.id) %></font>
      </td>
    </tr>
    <tr>
      <% if picture.image.present? %>
      <td colspan="3" width="400" height=auto><%= image_tag picture.image.url %></td>
    </tr>
    <tr>
        <% end %>
        <td colspan="3" width="400" height=auto><%= simple_format(picture.content) %></td>
    </tr>
    <tr>
        <td><%= link_to '詳細', picture_path(picture.id), class: "btn btn-outline-primary btn-sm" %></td>
        <% if current_user.id == picture.user.id %>
        <td><%= link_to "編集", edit_picture_path(picture.id), class: "btn btn-outline-primary btn-sm" %></td>
        <td><%= link_to "削除", picture_path(picture.id), method: :delete, data: { confirm: "本当に削除していいですか？"}, class: "btn btn-outline-primary btn-sm" %></td>
        <% end %>
    </tr>
    <% end %>
</table>


</div>
</div>
<div class="push"></div>

app/views/pictures/new.html.erb
<h2>画像を投稿する</h2>
<%= render 'form' %>

app/views/pictures/show.html.erb
<h1>投稿詳細画面</h1>
<% if @picture.image.present? %>
<%= image_tag @picture.image.url %><br>
<%= @picture.content %><br>
<% end %>


<% unless @picture.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(picture_id: @picture.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true, url: user_path ) do |form| %>
<% if @user.errors.any? %>
<div id="error_explanation">
    <h2><%= @user.errors.count %>件のエラーがあります。</h2>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="container">
  <font size="10rem"><%= @user.name %></font>

  <table align="center">
    <tr>
      <td>
    <%= image_tag(@user.avatar.url, size: "75") if @user.avatar && @user.avatar.url %>
      </td>
      <td>
    <%= form.file_field :avatar %><br>
    <%= form.hidden_field :avatar_cache %>
      </td>
    </tr>
    <tr>
      <td>
        <%= form.label :name %>
      </td>
      <td>
        <%= form.text_area :name, size: "60" %>
      </td>
    </tr>
    <tr>
      <td>
        <%= form.label :email %>
      </td>
      <td>
        <%= form.text_area :email, size: "60"  %>
      </td>
    </tr>



    <tr>
      <td colspan="2">
    <%= form.submit "更新する", class: 'btn btn-success' %>
      </td>
    </tr>
  </table>

<% end %>
</div>

app/views/users/new.html.erb
<div class="col-12">

<div class="mx-auto">

<h1>Pictgram</h1>
<h4>友達の写真や動画をチェックしよう</h4>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<br>
<span class="btn btn-primary">SNSbookでログイン</span><br>
<br>
--------または--------
<br>
<%= form_with(model: @user, local: true) do |f| %>
<div class="form-group">
  <%= f.text_field :name, class: "form-control", placeholder: "名前", size: "60" %><br>
  <%= f.email_field :email, class: "form-control", placeholder: "メールアドレス", size: "60" %><br>
  <%= f.password_field :password, class: "form-control", placeholder: "パスワード", size: "60" %><br>
  <%= f.password_field :password_confirmation, class: "form-control", placeholder: "確認用パスワード", size: "60" %><br>
  <%= f.file_field :avatar, class: "form-control" %><br>
  <%= f.hidden_field :avatar_cache, class: "form-control" %>
  <%= f.submit "登録する", class: 'btn btn-primary' %>
<% end %>
<br>
<br>
登録することで、SNSbookの利用規約、データに関するポリシー、Cookieポリシーに同意するものとします。
</div>

アカウントをお持ちですか？<%= link_to "ログイン", new_session_path %>

</div>


<div class="push"></div>

app/views/users/show.html.erb
<div class="container">
<div class="profile">

<div class="profile_img">
<%= image_tag(@user.avatar.url, size: "100") %>
</div>

<div class="profile_txt">
<font size="50"><%= @user.name %></font>
<%= link_to "プロフィールを編集", edit_user_path(@user.id) %>
</div>


</div>

</div>